In [14]:
# Import dependencies
import pandas as pd

#Read the data into a pandas dataframe
crowdfunding_data = pd.ExcelFile("crowdfunding.xlsx")

#Get the sheet names
crowdfunding_data.sheet_names

['crowdfunding_info', 'contact_info']

In [15]:
# create a dataframe from the crowdfunding_info sheet
crowdfunding_info_df = pd.read_excel(crowdfunding_data, sheet_name = 'crowdfunding_info')
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music

In [26]:
# Create a dataframe from the contact info worksheet
contact_info_df = pd.read_excel(crowdfunding_data, sheet_name = 'contact_info', header = 3) #header = 3 because the information is on the 4th line

#Increase the column width
pd.set_option('max_colwidth', 400) #So we can see the whole line

contact_info_df.head()

                                                                                contact_info
0   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
1          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
2            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
3  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
4        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}

In [17]:
# get brief summary of crowdfuning_info dataframe
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   company_name             1000 non-null   object
 2   blurb                    1000 non-null   object
 3   goal                     1000 non-null   int64
 4   pledged                  1000 non-null   int64
 5   outcome                  1000 non-null   object
 6   backers_count            1000 non-null   int64
 7   country                  1000 non-null   object
 8   currency                 1000 non-null   object
 9   launched_at              1000 non-null   int64
 10  deadline                 1000 non-null   int64
 11  staff_pick               1000 non-null   bool
 12  spotlight                1000 non-null   bool
 13  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(6), object(6)
memory usage: 95.8+ KB

In [18]:
#Get brief summary of the contact_info dataframe
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   contact_info  1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [19]:
# Get the unique values inthe category and subcategory column.
crowdfunding_info_df['category & sub-category'].unique()

array(['food/food trucks', 'music/rock', 'technology/web',
       'theater/plays', 'film & video/documentary',
       'music/electric music', 'film & video/drama', 'music/indie rock',
       'technology/wearables', 'publishing/nonfiction',
       'film & video/animation', 'games/video games',
       'film & video/shorts', 'publishing/fiction',
       'photography/photography books', 'publishing/radio & podcasts',
       'music/metal', 'music/jazz', 'publishing/translations',
       'film & video/television', 'games/mobile games',
       'music/world music', 'film & video/science fiction',
       'journalism/audio'], dtype=object)

In [20]:
#split the category and subcategory columns. Assign the values to df columns
crowdfunding_info_df[["category","subcategory"]] = crowdfunding_info_df["category & sub-category"].str.split('/', n=1, expand = True) #n=1 is number of splits. expand= true splits the string to seperate columns
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays,theater,plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary,film & video,documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays,theater,plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays,theater,plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music,music,electric music

In [21]:
# Create a unique identification number for each category and subcategory in it's respective column
# Getthe distinct values in the category and subcategory columns
print(crowdfunding_info_df['category'].nunique())
print(crowdfunding_info_df['subcategory'].nunique())

9
24

In [22]:
# Get the unique categories and subcategories in separate lists. 
categories = crowdfunding_info_df['category'].unique()
subcategories = crowdfunding_info_df['subcategory'].unique()

print(categories)
print()
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']

['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [23]:
#Create unique numbers for the categories and subcategories

# Import numpy
import numpy as np

#Create numpy arrays that have 1-10 for the category_ids and 1-25 for the subcategory_ids.
category_ids = np.arange(1,10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

In [24]:
# Use list comprehension to add 'cat0' to each category_id
cat_ids = ['cat0' + str(cat_id) for cat_id in category_ids]

# Use list comprehension to add "scat0" to each subcategory_id.
scat_ids = ['scat0' + str(scat_id) for scat_id in subcategory_ids]

print(cat_ids)
print(scat_ids)

['cat01', 'cat02', 'cat03', 'cat04', 'cat05', 'cat06', 'cat07', 'cat08', 'cat09']
['scat01', 'scat02', 'scat03', 'scat04', 'scat05', 'scat06', 'scat07', 'scat08', 'scat09', 'scat010', 'scat011', 'scat012', 'scat013', 'scat014', 'scat015', 'scat016', 'scat017', 'scat018', 'scat019', 'scat020', 'scat021', 'scat022', 'scat023', 'scat024']

In [25]:
# Create category_df and subcategory_df dataframes

# Create a category dataframe 
category_df = pd.DataFrame({
    'category_id': cat_ids,
    'category': categories
})

# Create a subcategory dataframe
subcategory_df = pd.DataFrame({
    "subcategory_id":scat_ids,
    "subcategory" : subcategories
})

print(category_df)
print(subcategory_df)

  category_id      category
0       cat01          food
1       cat02         music
2       cat03    technology
3       cat04       theater
4       cat05  film & video
5       cat06    publishing
6       cat07         games
7       cat08   photography
8       cat09    journalism
   subcategory_id        subcategory
0          scat01        food trucks
1          scat02               rock
2          scat03                web
3          scat04              plays
4          scat05        documentary
5          scat06     electric music
6          scat07              drama
7          scat08         indie rock
8          scat09          wearables
9         scat010         nonfiction
10        scat011          animation
11        scat012        video games
12        scat013             shorts
13        scat014            fiction
14        scat015  photography books
15        scat016   radio & podcasts
16        scat017              metal
17        scat018               jazz
18        scat019       translations
19        scat020         television
20        scat021       mobile games
21        scat022        world music
22        scat023    science fiction
23        scat024              audio

In [27]:
# Create a copy of the crowdfunding_info_df Dataframe as "campaign_df"
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [31]:
# Rename the 'blurb' launched_at' and 'deadline' columns
campaign_df = campaign_df.rename(columns={'blurb':'description', 'launched_at':'launch_date', 'deadline':'end_date'})
campaign_df

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2986,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks,food,food trucks
996,2031,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays,theater,plays
997,1627,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays,theater,plays
998,2175,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock,music,indie rock
999,1788,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks,food,food trucks

In [32]:
# Change the goal and pledged columns from int64 to float
campaign_df[['goal', 'pledged']] = campaign_df[['goal','pledged']].astype(float)
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [33]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt

campaign_df['launch_date']= pd.to_datetime(campaign_df['launch_date'], unit='s').dt.strftime('%Y-%m-%d')
campaign_df["end_date"] = pd.to_datetime(campaign_df["end_date"], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launch_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays